### ISSUE TITLE
[Question] Use multiple BlazorWebView on the same Window

### ISSUE THREAD

**Issue by am-kh** [jspuij/TwokaB#22]
Is it possible to use several BlazorWebView in the same WPF window? 
I tried to duplicate the BlazorView project and display two views in the same window but the blazor websites don't work properly.

![image](https://user-images.githubusercontent.com/18553382/85451456-33fc8680-b59a-11ea-8d32-a99ef496b0b1.png)

**Comment by jspuij** [comment]
No, that’s not possible. This project was forked from Steve Sandersons webwindow and there are a lot of Singletons in the codebase that prevent this. Is there a good usecase? I considered that most people would do the entire UI in Blazor anyway, so a single view would be enough.

**Comment by kestlerio** [comment]
> Is there a good usecase? 

Yes, I would have one: I intended to have a centered native canvas view (Direct2D on Windows, Canvas on Web, etc.) and have the toolbars (via BlazorWebView) around it (one on the left, one at the top, ...)

The BlazorHybridApp (Blazor Mobile Bindings) solution which emerged out of your work, does allow to have multiple Blazor views. However, they do not support WPF, but it's only Xamarin.Forms.

Anyway, thanks for the amazing work!

**Comment by jspuij** [comment]
With Mobile Blazor Bindings https://docs.microsoft.com/en-us/mobile-blazor-bindings/ this is now possible.
