### ISSUE TITLE
Unable to show images

### ISSUE THREAD

**Issue by musictopia2** [jspuij/TwokaB#23]
The only case I can't get this to work is if the blazor app uses images.  After lots of testing, I found that somehow a person has to copy the images to the wwwroot folder.  For server side and web assembly, it worked.
However, with the web control, when i do the same thing, still shows the image is not there.  If there was a way to get images without copying to wwwroot on the main project, that would be ever better.  As of now, the only case this does not work is if images was used either in svg or in img tag and its not an image from the internet.

**Comment by jspuij** [comment]
If you are using a shared library for the Blazor content, you have to place the images in the wwwroot folder of the shared library, but you must access them from a special location. Please read:

https://jspuij.github.io/BlazorWebView.Docs/pages/prepare.html#solve-some-runtime-problems
https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.1&tabs=visual-studio#consume-content-from-a-referenced-rcl

The special location is:

`_content/<Name.Of.Shared.Library/`

The build process will copy the content from the RCL to the special location during build.

**Comment by musictopia2** [comment]
That works with javascript files and css.  However, did not work with images.  I created a web assembly app and it worked perfectly but not with the webview.

**Comment by jspuij** [comment]
Is it possible for you to share the repo? I've been able to use images without issues. Let me see whether I can find something.

**Comment by musictopia2** [comment]
An example where I could not get images to work was with the default razor class library.  If I use img src for the default image, works fine with web assembly but does not work with the web control.

**Comment by jspuij** [comment]
@musictopia2 Which platform are you using? I'll include an image in one of the Tutorials for you.

**Comment by musictopia2** [comment]
I was using Windows WPF.

**Comment by jspuij** [comment]
@musictopia2, have a look at this branch:

https://github.com/jspuij/BlazorWebViewTutorial/tree/ImageTest

It will show the blazor logo on the index page.

**Comment by musictopia2** [comment]
Thanks.  I guess even for linking, you have to use the _content.  In the web assembly, that was not needed.  I was able to manually copy over and it worked.  I never would have guessed that _content can be used even for img src.

However, while I was waiting, I actually found a better solution.  For the purpose of what I needed, I actually put as embedded resource and then created an extension in order to display the image.  For the case I needed for reals, I am using svg and the image tag.  However, this is a good tutorial so if anybody else has problems, they can follow and use.
