### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by garrynewman** [jspuij/TwokaB#24]
Just noticed that the repo was renamed. What's happening? It's going to be available in a more official capacity? Should we be using this package anymore or switching to a different one?

**Comment by jspuij** [comment]
It is still available, you can use it without problems, but at a certain time when features are on par, you will be able to migrate to the MS version and use the Xamarin forms / MAUI Version of this component.

**Comment by garrynewman** [comment]
Will the new version be self contained like this version or is it included alongside a bunch of other stuff?

**Comment by jspuij** [comment]
It will probably contain the Mobile Blazor Bindings as well. But this is all still fluid, so we could take a request for a separate Nuget into consideration

**Comment by garrynewman** [comment]
My apprehension is really based on ignorance, because I don't know what the Mobile Blazor Bindings are. 

I'm using it to create [desktop windows for debug stuff for a game](https://files.facepunch.com/garry/1133f8b7-8c86-4352-a179-2e26a5856321.png), so when I hear "mobile" I worry that it doesn't work on desktop anymore.

**Comment by jspuij** [comment]
It will still work with WPF on the Desktop and it will work on the new unified MS display display technology called MAUI:
https://devblogs.microsoft.com/dotnet/introducing-net-multi-platform-app-ui/

You will also be able to render MAUI UI elements with Blazor instead of HTML.
