### ISSUE TITLE
Help: MSB3030 Could not copy the file `obj\Debug\netstandard2.1\compressed\_framework\_bin\Azure.Core.dll.br" because it was not found`

### ISSUE THREAD

**Issue by Smurf-IV** [jspuij/TwokaB#26]
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3030	Could not copy the file ".................\Prod\AdminWebUI\obj\Debug\netstandard2.1\compressed\_framework\_bin\Azure.Core.dll.br" because it was not found.	WpfHostAdminWebUI	C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	4651	

`AdminWebUI` is the target client side blazor app
`WpfHostAdminWebUI	`is the wrapper  wpf app following the steps in the "How to do on Windows"

Win 10 Pro x64
Visual Studio 2019 6.4 (or 6.5) Pro

Rinse and repeat error for every dll that is `gz` compressed within `AdminWebUI\bin\Debug\netstandard2.1\wwwroot\_framework\_bin`

**Comment by jspuij** [comment]
I’m not sure whether this is a fault of BlazorWebView. Anyway, I’m not near a computer for two weeks. I’ll look at it when I’m back in town.

**Comment by jspuij** [comment]
I'm afraid that your AdminWebUI is a Blazor WebAssembly app and not a RCL shared library. The first step should be to move (most of) the shared code into a Razor class library as indicated in:

https://jspuij.github.io/BlazorWebView.Docs/pages/prepare.html#add-a-shared-rcl-project
